/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package terrariaserver;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Razorbreak
 */
public class CheckPortDialog extends javax.swing.JDialog {

    /**
     * Creates new form CheckPortDialog
     */
    public CheckPortDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }
    
    private void realizarComprobacion(){
        String s=this.jTextField_ListaPuertos.getText();
        checkport.checkportTool chk = new checkport.checkportTool(this.jTextArea_ResultadosTestPuertos,
                                            s,this.jButton_ComprobarPuertos);
        Thread p = new Thread(chk);
        this.jButton_ComprobarPuertos.setEnabled(false);
        p.start();
        this.jTextField_ListaPuertos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_ListaPuertos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ResultadosTestPuertos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton_ComprobarPuertos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/language"); // NOI18N
        setTitle(bundle.getString("TEST DE PUERTOS")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText(bundle.getString("LISTA DE PUERTOS SEPARADOS POR COMAS:")); // NOI18N

        jTextField_ListaPuertos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ListaPuertosKeyPressed(evt);
            }
        });

        jTextArea_ResultadosTestPuertos.setColumns(20);
        jTextArea_ResultadosTestPuertos.setRows(5);
        jTextArea_ResultadosTestPuertos.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_ResultadosTestPuertos);

        jLabel2.setText(bundle.getString("ESTADO DE LOS PUERTOS:")); // NOI18N

        jButton_ComprobarPuertos.setText(bundle.getString("COMPROBAR...")); // NOI18N
        jButton_ComprobarPuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ComprobarPuertosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_ListaPuertos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton_ComprobarPuertos)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ListaPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ComprobarPuertos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ComprobarPuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ComprobarPuertosActionPerformed
        this.realizarComprobacion();
    }//GEN-LAST:event_jButton_ComprobarPuertosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(this.jButton_ComprobarPuertos.isEnabled()){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("lang/language").getString("POR FAVOR, ESPERE A QUE TERMINE EL TEST..."), java.util.ResourceBundle.getBundle("lang/language").getString("AVISO!"), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTextField_ListaPuertosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ListaPuertosKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.realizarComprobacion();
        }
    }//GEN-LAST:event_jTextField_ListaPuertosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckPortDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckPortDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckPortDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckPortDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckPortDialog dialog = new CheckPortDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ComprobarPuertos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_ResultadosTestPuertos;
    private javax.swing.JTextField jTextField_ListaPuertos;
    // End of variables declaration//GEN-END:variables
}
